apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-ex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-ex
    app.kubernetes.io/part-of: test-node
  name: nodejs-ex
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-ex
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-ex
    spec:
      containers:
      - image: quay.io/hacdev/user1-tenant/test-node/nodejs-ex@sha256:6acd83cbb2d36becd57c0224454c53a35d6bfa95a2d077904e90d3021d75bda6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
