apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-ex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-ex
    app.kubernetes.io/part-of: test-node
  name: nodejs-ex
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: nodejs-ex
status:
  loadBalancer: {}
