apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: nodejs-ex
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/user1-tenant/test-node/nodejs-ex@sha256:6acd83cbb2d36becd57c0224454c53a35d6bfa95a2d077904e90d3021d75bda6
        name: my-nodejs
        resources: {}
status: {}
