apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-ex
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-ex
    app.kubernetes.io/part-of: test-node
  name: nodejs-exbl7h
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: nodejs-ex
    weight: null
status: {}
